# -- Site settings --
baseurl:  # the subpath of your site, e.g. /blog/
url:  # the base hostname & protocol for your site
title: Anne Richardson
description: >
  Rails Developer
header_image: /img/headshot.jpg
email: richardson.ae@gmail.com
twitter_username: lortz
github_username:  lortza
linkedin_username: richardsonae
stackoverflow_profile: https://stackoverflow.com/users/5009528/richardsonae
# other_portfolio_url: http://localflavormarketing.com/

# -- Gems & Plugins --
plugins:
  - jekyll-redirect-from

# -- Build Settings --
markdown: kramdown
highlighter: rouge

# -- Pagination --
# plugins: [jekyll-paginate]
# paginate: 15
# paginate_path: "/blog/page:num/"

# -- Site Architecture --
collections:
  featured_projects:
    output: true
    permalink: /projects/:path/
  projects:
    output: true
    permalink: /projects/:path/
  products:
    output: true
    permalink: /products/:path/
  opensource_contributions:
    output: true
  writings:
    output: true
    permalink: /writing/:path/
